### ISSUE TITLE
[PE-D][Tester D] The app accept an partly wrong input

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S2-CS2113-W13-4/tp#103]
When I use add command with more than one /$ icon, the app still treated this as an accepted one.
I think the behavior is ok, but the input format is not correct.
![image.png](https://raw.githubusercontent.com/liuziyang020319/ped/main/files/2d5544ca-1be1-4219-aec1-35c1e56f18bf.png)

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: liuziyang020319/ped#20

**Comment by quanganh2810** [comment]
Fixed by updating the add command in the User Guide to say if there are more than one $/ or d/, the program accepts the first parameter specified.
