### ISSUE TITLE
[PE-D][Tester A] `list expenditure by category` fail after relaunching the application

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S2-CS2113-W13-4/tp#107]
![Screenshot 2023-03-31 at 5.56.54 PM.png](https://raw.githubusercontent.com/ZiqiuZeng/ped/main/files/76691be7-c6e1-4c59-bf54-6ff5f6c66ded.png)

After exit and relaunching the application, `list expenditure by category` cannot provide with the correct amount of expenditure added previously.

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: ZiqiuZeng/ped#10

**Comment by WilsonOh** [comment]
That is due to `list expenditure by category` not respecting the currency set. Fixed in #142
